mt_counties = {
    u'1': {'city': u'Butte', 'county': u'Silver Bow'},
    u'10': {'city': u'Red Lodge', 'county': u'Carbon'},
    u'11': {'city': u'Malta', 'county': u'Phillips'},
    u'12': {'city': u'Havre', 'county': u'Hill'},
    u'13': {'city': u'Hamilton', 'county': u'Ravalli'},
    u'14': {'city': u'Miles City', 'county': u'Custer'},
    u'15': {'city': u'Polson', 'county': u'Lake'},
    u'16': {'city': u'Glendive', 'county': u'Dawson'},
    u'17': {'city': u'Wolf Point', 'county': u'Roosevelt'},
    u'18': {'city': u'Dillon', 'county': u'Beaverhead'},
    u'19': {'city': u'Ft. Benton', 'county': u'Chouteau'},
    u'2': {'city': u'Great Falls', 'county': u'Cascade'},
    u'20': {'city': u'Glasgow', 'county': u'Valley'},
    u'21': {'city': u'Shelby', 'county': u'Toole'},
    u'22': {'city': u'Hardin', 'county': u'Big Horn'},
    u'23': {'city': u'Roundup', 'county': u'Musselshell'},
    u'24': {'city': u'Chinook', 'county': u'Blaine'},
    u'25': {'city': u'Virginia City', 'county': u'Madison'},
    u'26': {'city': u'Conrad', 'county': u'Pondera'},
    u'27': {'city': u'Sidney', 'county': u'Richland'},
    u'28': {'city': u'Deer Lodge', 'county': u'Powell'},
    u'29': {'city': u'Forsyth', 'county': u'Rosebud'},
    u'3': {'city': u'Billings', 'county': u'Yellowstone'},
    u'30': {'city': u'Anaconda', 'county': u'Deer Lodge'},
    u'31': {'city': u'Choteau', 'county': u'Teton'},
    u'32': {'city': u'Columbus', 'county': u'Stillwater'},
    u'33': {'city': u'Hysham', 'county': u'Treasure'},
    u'34': {'city': u'Plentywood', 'county': u'Sheridan'},
    u'35': {'city': u'Thompson Falls', 'county': u'Sanders'},
    u'36': {'city': u'Stanford', 'county': u'Judith Basin'},
    u'37': {'city': u'Scobey', 'county': u'Daniels'},
    u'38': {'city': u'Cut Bank', 'county': u'Glacier'},
    u'39': {'city': u'Baker', 'county': u'Fallon'},
    u'4': {'city': u'Missoula', 'county': u'Missoula'},
    u'40': {'city': u'Big Timber', 'county': u'Sweet Grass'},
    u'41': {'city': u'Circle', 'county': u'McCone'},
    u'42': {'city': u'Ekalaka', 'county': u'Carter'},
    u'43': {'city': u'Townsend', 'county': u'Broadwater'},
    u'44': {'city': u'Harlowton', 'county': u'Wheatland'},
    u'45': {'city': u'Terry', 'county': u'Prairie'},
    u'46': {'city': u'Philipsburg', 'county': u'Granite'},
    u'47': {'city': u'White Sulphur Springs', 'county': u'Meagher'},
    u'48': {'city': u'Chester', 'county': u'Liberty'},
    u'49': {'city': u'Livingston', 'county': u'Park'},
    u'5': {'city': u'Helena', 'county': u'Lewis & Clark'},
    u'50': {'city': u'Jordan', 'county': u'Garfield'},
    u'51': {'city': u'Boulder', 'county': u'Jefferson'},
    u'52': {'city': u'Wibaux', 'county': u'Wibaux'},
    u'53': {'city': u'Ryegate', 'county': u'Golden Valley'},
    u'54': {'city': u'Superior', 'county': u'Mineral'},
    u'55': {'city': u'Winnett', 'county': u'Petroleum'},
    u'56': {'city': u'Libby', 'county': u'Lincoln'},
    u'6': {'city': u'Bozeman', 'county': u'Gallatin'},
    u'7': {'city': u'Kalispell', 'county': u'Flathead'},
    u'8': {'city': u'Lewistown', 'county': u'Fergus'},
    u'9': {'city': u'Broadus', 'county': u'Powder River'}
}
