"""empty message

Revision ID: 1d0442758bfb
Revises: 2f8cb1401dd0
Create Date: 2015-08-16 21:59:56.248774

"""

# revision identifiers, used by Alembic.
revision = '1d0442758bfb'
down_revision = '2f8cb1401dd0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
