"""empty message

Revision ID: 2f8cb1401dd0
Revises: 3881d6979eaa
Create Date: 2015-08-16 21:59:08.166808

"""

# revision identifiers, used by Alembic.
revision = '2f8cb1401dd0'
down_revision = '3881d6979eaa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valid_riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valid_riders')
    ### end Alembic commands ###
